openapi: 3.0.3
info:
  title: API de Personajes
  description: API REST para autenticación y gestión de personajes en base de datos SQL Server.
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Servidor local de desarrollo

paths:
  /login:
    post:
      summary: Autenticación de usuario
      description: Valida las credenciales de un usuario y establece una sesión si son correctas.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: usuario1
                password:
                  type: string
                  example: secret123
              required:
                - username
                - password
      responses:
        '200':
          description: Autenticación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: Autenticacion exitosa
        '400':
          description: Faltan credenciales
        '401':
          description: Credenciales incorrectas
        '500':
          description: Error en base de datos o conexión

  /personajes:
    get:
      summary: Obtener todos los personajes
      description: Devuelve la lista de personajes registrados en la base de datos.
      responses:
        '200':
          description: Lista de personajes obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Personaje'
        '500':
          description: Error al obtener personajes
    post:
      summary: Crear un nuevo personaje
      description: Agrega un nuevo personaje a la base de datos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Personaje'
      responses:
        '201':
          description: Personaje creado exitosamente
        '400':
          description: Datos incompletos
        '500':
          description: Error al crear personaje

  /personajes/{id}:
    get:
      summary: Obtener personaje por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID del personaje
      responses:
        '200':
          description: Personaje encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Personaje'
        '404':
          description: Personaje no encontrado
        '500':
          description: Error al obtener personaje

    put:
      summary: Actualizar un personaje existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID del personaje
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Luke Skywalker
                email:
                  type: string
                  example: luke@rebellion.com
      responses:
        '200':
          description: Personaje actualizado exitosamente
        '400':
          description: Datos incompletos
        '404':
          description: Personaje no encontrado
        '500':
          description: Error al actualizar personaje

    delete:
      summary: Eliminar un personaje por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID del personaje
      responses:
        '200':
          description: Personaje eliminado exitosamente
        '404':
          description: Personaje no encontrado
        '500':
          description: Error al eliminar personaje

components:
  schemas:
    Personaje:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Mario Bros
        email:
          type: string
          example: mario@nintendo.com
      required:
        - id
        - name
        - email